# This is some comments for autogenerated stuff
# End of comments
# Yeah...
{
    anObj : {
        someEl : [ SOME, stupid, "striins, ", "diadia" ],
# Another comment
        someEl2 : [ { i : 2 } , { i : 1 } ],
        someasset : "KAKA2",
        anotherstring : "some other string",
        anArray : [66, 2,3 ,4, 5, 5]
    } 
}  
 

