/*
Block script sample program
*/
struct PsyBeadsState
{
	screenRatio : float;
	time : float;
	padding : float2;
};
#define TEST_SZ 1251213

psyBeadsProgram = LoadProgram("Programs/PSyBeadsRayMarcher.pas");
beadsState = PsyBeadsState(); 
beadsStateUniform = GetUniformLocation(psyBeadsProgram, "uniformState");
beadsStateBuffer = CreateUniformBuffer(sizeof(PsyBeadsState));

quad = CreateMesh();
quadGenerator = CreateMeshGenerator("QuadGenerator");
quad->SetGeneratorInput(quadGenerator);
dd = quadGenerator;

int echoF(ab: float2)
{
	echo(ab.x);
	echo(ab.y);
}
int Timeline_Update(beat : float)
{
	quadGenerator.QuadExtends = float2(1.0,1.0);
	echo(TEST_SZ);
}

int Timeline_Render(beat : float)
{
	beadsState.screenRatio = beat * 400.0 / 350.0;
	beadsState.time = 5.0 * beat;

	SetProgram(psyBeadsProgram);
	SetBuffer(beadsStateBuffer, beadsState);
	SetUniformBuffer(beadsStateUniform, beadsStateBuffer);
	SetMesh(quad);
	Draw();
}