f1 = float3(1,2,3);
f2 = float3(2,1,3);

dr = dot(f1.xxyz,f2.zzyy);
echo(dr);

i = 0;
while(i <= 2)
{
    f1[i] = i;
    f2[i] = i;
    i = i + 1;
}
echo(dot(f1,f2));

(f1 + f2)[2] = 2;


mm = float3x3(
        float3(0,1,2),
        float3(2,3,4),
        float3(3,4,5)
     );

pp = mm;


i = 0;
while (i < 3)
{
    pp[i][i] = 0.99;
    i = i + 1;
}

float3x3 getTransform(ff : float)
{
    return float3x3(
        float3(ff,0.0,0.0),
        float3(0.0,ff,0.0),
        float3(0.0,0.0,ff)
    );
}

tt =  float3(getTransform(1.0)[0].x, getTransform(2.0)[1].y, getTransform(3.0)[2].z).xyz;
echo(dot(tt,tt));

/// Testing lerp

val1 = float2(1.0,0.0);
val2 = val1.yx;
r = lerp(val1,val2,0.5);

echo(r.x);
echo(r.y);


#define arr_sz 10
transform_arrays = static_array<float2x2[arr_sz]>;
i = 0;
while (i < arr_sz)
{
    transform_arrays[i] = float2x2(
        10.0, 1.0,
        20.0, 2.0
      );
    i = i + 1;
}

i = 0;
while (i < arr_sz)
{
    echo(mul(transform_arrays[i],r).x); //5.5
    echo(mul(transform_arrays[i],r).y); //11.0
    i = i + 1;
}



